---
kind: pipeline
name: default


steps:
  - name: linter
    image: snakepacker/python:pylava
    pull: always
    commands:
      - pylava -o pylava.ini .

  - name: prepare toxenv
    image: snakepacker/python:all
    group: tests
    pull: always
    commands:
      - tox --notest
    volumes:
      - name: cache
        path: /drone/src/.tox

  - name: checkdoc
    image: snakepacker/python:all
    group: tests
    pull: always
    commands:
      - tox
    environment:
      TOXENV: checkdoc
    volumes:
      - name: cache
        path: /drone/src/.tox

  - name: python 3.5
    image: snakepacker/python:all
    group: tests
    pull: always
    commands:
      - tox
    environment:
      TOXENV: py35
      COVERALLS_REPO_TOKEN:
        from_secret: COVERALLS_TOKEN
    volumes:
      - name: cache
        path: /drone/src/.tox

  - name: python 3.6
    image: snakepacker/python:all
    group: tests
    pull: always
    commands:
      - tox
    environment:
      TOXENV: py36
      COVERALLS_REPO_TOKEN:
        from_secret: COVERALLS_TOKEN
    volumes:
      - name: cache
        path: /drone/src/.tox

  - name: python 3.7
    image: snakepacker/python:all
    group: tests
    pull: always
    commands:
      - tox
    environment:
      TOXENV: py37
      COVERALLS_REPO_TOKEN:
        from_secret: COVERALLS_TOKEN
    volumes:
      - name: cache
        path: /drone/src/.tox

  - name: python 3.7 uvloop
    image: snakepacker/python:all
    group: tests
    pull: always
    commands:
      - tox
    environment:
      TOXENV: uvloop
      COVERALLS_REPO_TOKEN:
        from_secret: COVERALLS_TOKEN
    volumes:
      - name: cache
        path: /drone/src/.tox

  - name: python 3.6 contextvars
    image: snakepacker/python:all
    group: tests
    pull: always
    commands:
      - tox
    environment:
      TOXENV: contextvars36
      COVERALLS_REPO_TOKEN:
        from_secret: COVERALLS_TOKEN
    volumes:
      - name: cache
        path: /drone/src/.tox

  - name: RPC example
    image: snakepacker/python:all
    group: tests
    pull: always
    commands:
      - tox
    environment:
      TOXENV: rpc
      COVERALLS_REPO_TOKEN:
        from_secret: COVERALLS_TOKEN
    volumes:
      - name: cache
        path: /drone/src/.tox

  - name: notify
    image: drillster/drone-email
    settings:
      host:
        from_secret: SMTP_HOST
      username:
        from_secret: SMTP_USERNAME
      password:
        from_secret: SMTP_PASSWORD
      from:
        from_secret: SMTP_USERNAME
      when:
        status:
          - changed
          - failure

volumes:
  - name: cache
    temp: {}

---
kind: signature
hmac: 226cb7a3d3028149644cce8d3bd23b0655208fd26adab1b8d25aa68d488d7483

...
